=== api-evangelist/amazon-step-functions/json-schema/amazon-step-functions-describe-state-machine-for-execution-output-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-step-functions/refs/heads/main/json-schema/amazon-step-functions-describe-state-machine-for-execution-output-schema.json",
  "title": "DescribeStateMachineForExecutionOutput",
  "description": "DescribeStateMachineForExecutionOutput schema from Amazon Step Functions API",
  "type": "object",
  "properties": {
    "stateMachineArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the state machine associated with the execution."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The name of the state machine associated with the execution."
        }
      ]
    },
    "definition": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Definition"
        },
        {
          "description": "The Amazon States Language definition of the state machine. See <a href=\"https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html\">Amazon States Language</a>."
        }
      ]
    },
    "roleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the IAM role of the State Machine for the execution. "
        }
      ]
    },
    "updateDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The date and time the state machine associated with an execution was updated. For a newly created state machine, this is the creation date."
        }
      ]
    },
    "loggingConfiguration": {
      "$ref": "#/components/schemas/LoggingConfiguration"
    },
    "tracingConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TracingConfiguration"
        },
        {
          "description": "Selects whether X-Ray tracing is enabled."
        }
      ]
    },
    "mapRunArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the Map Run that started the child workflow execution. This field is returned only if the <code>executionArn</code> is a child workflow execution that was started by a Distributed Map state."
        }
      ]
    },
    "label": {
      "allOf": [
        {
          "$ref": "#/components/schemas/MapRunLabel"
        },
        {
          "description": "A user-defined or an auto-generated string that identifies a <code>Map</code> state. This \ufb01eld is returned only if the <code>executionArn</code> is a child workflow execution that was started by a Distributed Map state."
        }
      ]
    },
    "revisionId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RevisionId"
        },
        {
          "description": "<p>The revision identifier for the state machine. The first revision ID when you create the state machine is null.</p> <p>Use the state machine <code>revisionId</code> parameter to compare the revision of a state machine with the configuration of the state machine used for executions without performing a diff of the properties, such as <code>definition</code> and <code>roleArn</code>.</p>"
        }
      ]
    }
  },
  "required": [
    "stateMachineArn",
    "name",
    "definition",
    "roleArn",
    "updateDate"
  ]
}

=== api-evangelist/amazon-step-functions/examples/amazon-step-functions-describe-state-machine-for-execution-output-example.json
{
  "stateMachineArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "name": "MyResource",
  "definition": "example-value",
  "roleArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "updateDate": "example-value",
  "loggingConfiguration": "example-value",
  "tracingConfiguration": "example-value",
  "mapRunArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "label": "example-value",
  "revisionId": "example-value"
}
